version: '3'
services:
    proxy:
        build: ./proxy
        ports:
            - "5000:5000"
        depends_on:
            - app
        networks:
            - front
    app:
        image: redis:3.2.0
        build: ./app
        networks:
            - front
            - back
    db:
        image: postgres
        networks:
            - back
    
networks:
    front:
        driver: custom-driver-1
    back:
        driver: bridge
        driver_opts:
            foo: "1"
            bar: "2"